--CREATE DATABASE 
-- Entity Relationship Model 
-- https://medium.com/omarelgabrys-blog/database-modeling-entity-relationship-diagram-part-5-352c5a8859e5
-- MYSQL DOES NOT HAVE TWO CONCEPTS REGARDING SCHEMA AND DATABASE LIKE ORACLE HAS 
CREATE DATABASE IF NOT EXISTS NONAPORTA; 

--STATIC TABLES ID SHOULD BE OF SMALLINT DATATYPE
-- THE TOKENS WILL CONTAIN 3 CHAR TO IDENTIFY THE TABLE
-- 6 CHAR TO IDENTIFY THE DATA ITSELF
CREATE TABLE IF NOT EXISTS NONAPORTA.STATIC_DATA_GENDER(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
TOKEN CHAR(9) NOT NULL UNIQUE,
DESC VARCHAR(20),
INDEX (TOKEN)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.STATIC_DATA_PROFESSION(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
TOKEN CHAR(9) NOT NULL UNIQUE,
DESC VARCHAR(20),
INDEX (TOKEN)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.MESSAGE_RESOURCES(
ID INT PRIMARY KEY AUTO_INCREMENT,
LANGUAGE CHAR(2),
TOKEN VARCHAR(50)
MESSAGE TEXT,
INDEX (TOKEN)
);

--USER
--USER_FACEBOOK
--USER_TWITTER
--MODEL
--MODEL_FACEBOOK
--MODEL TWITTER
CREATE TABLE IF NOT EXISTS NONAPORTA.ROLES(
ID TINYINT PRIMARY KEY AUTO_INCREMENT,
TOKEN CHAR(10),
DESC VARCHAR(20),
INDEX (TOKEN)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.THEMES(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
THEME_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS NONAPORTA.SERVICES(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
SERVICE_NAME VARCHAR(30) NOT NULL,
ACTIVE BIT
);

CREATE TABLE IF NOT EXISTS NONAPORTA.MODELS_SERVICES();

--User Tables 
--CREATE TABLE pet (name VARCHAR(20), owner VARCHAR(20), species VARCHAR(20), sex CHAR(1), birth DATE, death DATE); 
--HOW STORE PASSWORDS USERS ? 
-- USE HASH ALGORITHM SHA-256 , ALL THE HASHES HAS THE SAME LENGHT 
-- TWO EQUALS PASSWORDS GENERATE THE SAME HASH SO THE CROOKERS CAN GENERATE RAINBOWS TABLES TO MATCH 
-- USE SALT -> SO WE ARE PREVENTING TWO EQUAL PASSWORDS TO HAVE THE SAME HASH AND TO PREVENT RAINBOWS TABLES ATTACK !!! 
-- BUT WHERE DO WE STORE THE SALT , IF AN ATTACKER HAS ACCESS TO THE DATABASE HW WILL HAS ACCESS TO SALT 
-- THE RAINBOWS TABLES ARE CREATED IN THE ADVANCE AND DISTRIBUTED EN MASS TO SAVE CALCULATIONS FOR OTHERS SO HAVING ACCESS TO THE SALT 
-- http://www.appsdeveloperblog.com/encrypt-user-password-example-java/ 
-- https://security.stackexchange.com/questions/11221/how-big-should-salt-be 
-- https://howtodoinjava.com/security/how-to-generate-secure-password-hash-md5-sha-pbkdf2-bcrypt-examples/ 
-- https://blogs.msdn.microsoft.com/tzink/2012/08/29/how-rainbow-tables-work/ 
-- INSTEAD OF USING AN CRYPTOGRAPHICALLY SECURE HASH FUNCTION (SHA) WE WILL USE AN PASSWORD BASED KEY DERIVATION FUNCTION 
-- THIS FUNCTION WILL BE SLOW ENOUGH TO IMPEDE THE ATTACK BUT STILL FAST ENOUGH TO NOT CAUSE A NOTICEABLE DELAY FOR THE USE. 
-- THESE ALGORITHMS TAKE A WORK FACTOR (ALSO KNOWN AS SECURITY FACTOR) OR ITERATION COUNT AS AN ARGUMENT. THIS VALUE DETERMINES HOW SLOW THE HASH FUNCTION WILL BE. 
-- WHEN COMPUTERS BECOME FASTER NEXT YEAR WE CAN INCREASE THE WORK FACTOR TO BALANCE IT OUT. 
-- WE GONNA USE THE org.springframework.security.crypto.bcrypt.BCrypt CLASS TO GENERATE THE HASH AND THE SALT AND TO COMPARE PASSWORDS 
-- THE BCRYPT HASHES FOLLOW A STRUCTURE REFERRED TO AS A MODULAR CRYPT FORMAT(MCF)
-- $<id>$<cost>$<salt><digest>
-- VARCHAR IS VARIABLE LENGHT / CHAR IS FIXED LENGHT
-- THEY ALSO DIFFER IN MAXIMUM LENGTH AND IN WHETHER TRAILING SPACES ARE RETAINED !!!
-- 
-- CHAR(60) || BINARY || BINARY(60) 
-- WE GONNA USE TWO FACTOR AUTHENTICATION THROUGH TWILIO API(SMS API)
-- The users will have the chance to authenticate through Facebook or Gmail , we will use the OAuth protocol for that purpose.
--  It uses username and password tokens instead 
-- OAuth 2.0 is a simple protocol that allows to access resources of the user without sharing passwords.
-- developers.facebook.com
-- http://javapapers.com/java/java-facebook-login-with-oauth-authentication/
-- https://developers.facebook.com/docs/facebook-login/web
-- https://spring.io/guides/gs/accessing-facebook/
-- http://restfb.com/
-- http://www.baeldung.com/facebook-authentication-with-spring-security-and-social
-- Should we use CDN https://www.cloudflare.com/learning/cdn/what-is-a-cdn/ ?
CREATE TABLE IF NOT EXISTS NONAPORTA.USERS_LOGIN ( 
        ID INT PRIMARY KEY AUTO_INCREMENT, 
        LOGIN_NAME VARCHAR NOT NULL , 
        PASSWORD NOT NULL BINARY(60) ,
		LAST_LOGIN DATETIME NOT NULL,
		ROLE NOT NULL TINYINT,
		EXTERNAL_ID BIGINT,
		PHONE_NUMER CHAR(10), 
		DOUBLE_FACT_AUTH NOT NULL CHAR(1),
		FOREIGN KEY(ROLE) REFERENCES NONAPORTA.ROLES(ID)
); 

-- Date parts must always be given in year-month-day order!!!
CREATE TABLE IF NOT EXISTS NONAPORTA.USERS_INFORMATION( 
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL, 
LAST_NAME VARCHAR(20) NOT NULL, 
MAIL NOT NULL VARCHAR(255), 
REGISTER_DATE DATETIME NOT NULL, 
GENDER SMALLINT NOT NULL, 
PHOTO , 
PROFESSION SMALLINT,
ACTIVE CHAR(1),
FOREIGN KEY (ID) REFERENCES NONAPORTA.USERS_LOGIN(ID),
FOREIGN KEY (PROFESSION) REFERENCES NONAPORTA.STATIC_DATA_PROFESSION(ID),
FOREIGN KEY (GENDER) REFERENCES NONAPORTA.STATIC_DATA_GENDER(ID)
);


-- We will use GOOGLE MAPS API to mark the map with the models location
-- We load the map with all know models locations and the calculations are made in real time in the client side
-- through Google Maps Javascript API.
-- We will also use the Google Maps Geocoding API to get the geographic coordinates from address and store them 
-- in the database
-- https://developers.google.com/maps/documentation/javascript/mysql-to-maps#createtable
-- https://stackoverflow.com/questions/32284708/how-to-constantly-detect-nearby-marker-locations-from-current-location-in-google
-- https://github.com/googlemaps/google-maps-services-java/tree/master/src/main/java/com/google/maps
-- https://developers.google.com/maps/faq#geocoder_queryformat
-- https://developers.google.com/maps/documentation/javascript/tutorial
CREATE TABLE IF NOT EXISTS NONAPORTA.MODELS_INFORMATION(
ID INT PRIMARY KEY,
ADDRESS VARCHAR(255),
LAT FLOAT( 10, 6 ) ,
LNG FLOAT( 10, 6 ) ,
FOREIGN KEY(ID) REFERENCES NONAPORTA.USERS_INFORMATION(ID)
);

-- AWS S3
-- Storage Class
-- 	Frequent access
--  Standard for infrequent access
--  Amazon Glacier
--  How data is organized ?
--  Bucket (Logical unit of storagge)
--   Bucket contains objects which contain data and metadata(name-value pair)
-- https://www.edureka.co/blog/s3-aws-amazon-simple-storage-service/
-- Object locking is not supported in Amazon S3. This means that if our application needs to protect an existing object against modifications from other processes, 
-- we have to implement this functionality in our own application
-- https://www.javacodegeeks.com/2017/03/amazon-s3-tutorial.html#cli_buckets
-- http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html Generate KEYS (Key Name prefixes)
-- http://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html
-- The purpose of the prefix and delimiter parameters is to help you organize and then browse your keys hierarchically.
-- Key Format
-- Delimiter "/"
-- modelId/dataType/year/session/photoId/versionId

CREATE TABLE IF NOT EXISTS NONAPORTA.USER_SERVICES(
USER_ID INT NOT NULL,
SERVICE_ID SMALLINT NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES NONAPORTA.USERS_LOGIN(ID),
FOREIGN KEY(SERVICE_ID) REFERENCES NONAPORTA.SERVICES(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.USER_SERVICES_HISTORY(
USER_ID INT NOT NULL,
SERVICE_ID SMALLINT NOT NULL,
REGISTER_DATE DATETIME NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES NONAPORTA.USERS_LOGIN(ID),
FOREIGN KEY(SERVICE_ID) REFERENCES NONAPORTA.SERVICES(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.PHOTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
MODEL INT,
SESSION SMALLINT NOT NULL,
DATE DATETIME NOT NULL, 
FOREIGN KEY(MODEL) REFERENCES NONAPORTA.MODELS_INFORMATION(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.PHOTOS_VERSIONS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ORIGINAL INT,
THEME SMALLINT,
KEY_PATH VARCHAR(100),
FOREIGN KEY(ORIGINAL) REFERENCES NONAPORTA.PHOTOS(ID)
FOREIGN KEY(THEME) REFERENCES NONAPORTA.THEMES(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.ACTIVE_PHOTOS(
ID INT PRIMARY KEY,
ORDER TINYINT NOT NULL,
FOREIGN KEY(ID) REFERENCES NONAPORTA.PHOTO_VERSIONS(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.ACTIVE_PHOTOS_HISTORY(
ID INT PRIMARY KEY,
ORDER TINYINT,
ACTIVE_DATE DATETIME,
FOREIGN KEY(ID) REFERENCES NONAPORTA.PHOTOS_VERSIONS(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.VIDEOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
MODEL INT,
SESSION SMALLINT NOT NULL,
DATE DATETIME NOT NULL,
FOREIGN KEY(MODEL) REFERENCES NONAPORTA.MODELS_INFORMATION(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.VIDEOS_VERSIONS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ORIGINAL INT,
THEME SMALLINT,
KEY_PATH VARCHAR(100),
FOREIGN KEY(ORIGINAL) REFERENCES NONAPORTA.VIDEOS(ID)
FOREIGN KEY(THEME) REFERENCES NONAPORTA.THEMES(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.ACTIVE_VIDEOS(
ID INT PRIMARY KEY,
ORDER TINYINT NOT NULL,
FOREIGN KEY(ID) REFERENCES NONAPORTA.VIDEOS_VERSIONS(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.ACTIVE_VIDEOS_HISTORY(
ID INT PRIMARY KEY,
ORDER TINYINT,
ACTIVE_DATE DATETIME,
FOREIGN KEY(ID) REFERENCES NONAPORTA.VIDEOS_VERSIONS(ID)
);

CREATE TABLE IF NOT EXISTS NONAPORTA.PAYMENTS(
ID INT PRIMARY KEY AUTO_INCREMENT,

);

